### ISSUE TITLE
Sidekiq web integration

### ISSUE THREAD

**Issue by mickey** [ankane/clockwork_web#1]
Hey guys,
Just stumble upon your gem and loves it :heart_eyes: 

I wrote a small extension allowing it to be embedded inside Sidekiq Web.

![](https://s3.amazonaws.com/f.cl.ly/items/2e0R2H1F3114220H1F1T/Screen%20Shot%202016-02-03%20at%2002.58.05.png?v=3b5724a7)

The implementation is really simple https://gist.github.com/mickey/f3a8d0b2593b995c1f94.

Would you be interested in a PR or should I publish this as an external gem?

**Comment by ankane** [comment]
Hey @mickey, pretty cool. I think an external gem makes the most sense.
