### ISSUE TITLE
Temporarily disable a scheduled job

### ISSUE THREAD

**Issue by seanhandley** [ankane/clockwork_web#2]
The ability to disable a scheduled job is very useful when debugging issues but there's a risk of failing to enable the jobs again afterwards.

I'd like to see a feature in the UI where you can "Disable for ..." (pick hours, minutes).

If that's something you'd be interested in merging @ankane then I'm happy to write up the code in a pull request.

**Comment by ankane** [comment]
Hey @seanhandley, sorry for not responding earlier. Happy to add it if you want to put something together.

**Comment by seanhandley** [comment]
FYI I doubt I'll get around to this - I've switched jobs and no longer use clockwork.

**Comment by ankane** [comment]
No worries
